from typing import Any

from app.templates.models import TemplateStatus, TemplateType


def layer(layer_id: str, layer_type: str, **values: Any) -> dict[str, Any]:
    return {
        "id": layer_id,
        "type": layer_type,
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0,
        "rotation": 0,
        "opacity": 1,
        "visible": True,
        "locked": False,
        "zIndex": 0,
        **values,
    }


def document(*layers: dict[str, Any]) -> dict[str, Any]:
    return {"schemaVersion": "1.0", "layers": list(layers), "metadata": {"demo": True}}


DEMO_TEMPLATES: tuple[dict[str, Any], ...] = (
    {
        "id": "20000000-0000-4000-8000-000000000001",
        "name": "白底主图",
        "code": "MAIN_WHITE_01",
        "template_type": TemplateType.MAIN,
        "status": TemplateStatus.ACTIVE,
        "canvas_width": 1600,
        "canvas_height": 1600,
        "background": {"color": "#ffffff"},
        "schema_json": document(
            layer(
                "product",
                "IMAGE",
                x=160,
                y=120,
                width=1280,
                height=1280,
                zIndex=1,
                assetSource="{{asset.cutout}}",
                fit="contain",
            )
        ),
    },
    {
        "id": "20000000-0000-4000-8000-000000000002",
        "name": "基础长宽尺寸图",
        "code": "DIMENSION_BASIC_01",
        "template_type": TemplateType.DIMENSION,
        "status": TemplateStatus.ACTIVE,
        "canvas_width": 1600,
        "canvas_height": 1600,
        "background": {"color": "#f7f8fa"},
        "schema_json": document(
            layer(
                "product",
                "IMAGE",
                x=350,
                y=230,
                width=900,
                height=900,
                zIndex=1,
                assetSource="{{asset.cutout}}",
                fit="contain",
            ),
            layer(
                "width-line",
                "LINE",
                x=350,
                y=1210,
                width=900,
                height=30,
                zIndex=2,
                points=[0, 0, 900, 0],
                stroke="#172033",
                strokeWidth=3,
                arrowStart=True,
                arrowEnd=True,
            ),
            layer(
                "width-text",
                "TEXT",
                x=500,
                y=1260,
                width=600,
                height=80,
                zIndex=3,
                text="{{product.width}}",
                fontSize=48,
                fontFamily="Arial",
                fontWeight="bold",
                align="center",
                lineHeight=1.2,
                fill="#172033",
            ),
            layer(
                "height-line",
                "LINE",
                x=260,
                y=300,
                width=30,
                height=760,
                zIndex=2,
                points=[0, 0, 0, 760],
                stroke="#172033",
                strokeWidth=3,
                arrowStart=True,
                arrowEnd=True,
            ),
            layer(
                "height-text",
                "TEXT",
                x=30,
                y=650,
                width=190,
                height=80,
                zIndex=3,
                text="{{product.height}}",
                fontSize=42,
                fontFamily="Arial",
                fontWeight="bold",
                align="right",
                lineHeight=1.2,
                fill="#172033",
            ),
        ),
    },
    {
        "id": "20000000-0000-4000-8000-000000000003",
        "name": "三个核心卖点",
        "code": "SELLING_POINT_01",
        "template_type": TemplateType.SELLING_POINT,
        "status": TemplateStatus.ACTIVE,
        "canvas_width": 1600,
        "canvas_height": 1600,
        "background": {"color": "#f7f8f6"},
        "schema_json": document(
            layer(
                "product",
                "IMAGE",
                x=60,
                y=280,
                width=800,
                height=1040,
                zIndex=1,
                assetSource="{{asset.cutout}}",
                fit="contain",
            ),
            layer(
                "eyebrow",
                "TEXT",
                x=900,
                y=205,
                width=600,
                height=50,
                zIndex=2,
                text="PRODUCT HIGHLIGHTS",
                fontSize=22,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1.2,
                fill="#a26332",
            ),
            layer(
                "title",
                "TEXT",
                x=900,
                y=260,
                width=610,
                height=130,
                zIndex=2,
                text="{{product.name}}",
                fontSize=52,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1.12,
                fill="#182238",
            ),
            layer(
                "title-rule",
                "LINE",
                x=900,
                y=405,
                width=560,
                height=0,
                zIndex=2,
                points=[0, 0, 560, 0],
                stroke="#d6d9d5",
                strokeWidth=2,
            ),
            layer(
                "number-1",
                "TEXT",
                x=900,
                y=515,
                width=90,
                height=80,
                zIndex=2,
                text="01",
                fontSize=62,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1,
                fill="#c6a174",
            ),
            layer(
                "point-1-title",
                "TEXT",
                x=1015,
                y=525,
                width=480,
                height=55,
                zIndex=2,
                text="{{selling_point_1}}",
                fontSize=38,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1.2,
                fill="#202a3f",
            ),
            layer(
                "point-1-description",
                "TEXT",
                x=1015,
                y=600,
                width=480,
                height=45,
                zIndex=2,
                text="{{sku.selling_point_description_1}}",
                fontSize=24,
                fontFamily="Arial",
                fontWeight="normal",
                align="left",
                lineHeight=1.2,
                fill="#687184",
            ),
            layer(
                "point-1-rule",
                "LINE",
                x=1015,
                y=680,
                width=480,
                height=0,
                zIndex=2,
                points=[0, 0, 480, 0],
                stroke="#e1e3df",
                strokeWidth=2,
            ),
            layer(
                "number-2",
                "TEXT",
                x=900,
                y=745,
                width=90,
                height=80,
                zIndex=2,
                text="02",
                fontSize=62,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1,
                fill="#c6a174",
            ),
            layer(
                "point-2-title",
                "TEXT",
                x=1015,
                y=755,
                width=480,
                height=55,
                zIndex=2,
                text="{{selling_point_2}}",
                fontSize=38,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1.2,
                fill="#202a3f",
            ),
            layer(
                "point-2-description",
                "TEXT",
                x=1015,
                y=830,
                width=480,
                height=45,
                zIndex=2,
                text="{{sku.selling_point_description_2}}",
                fontSize=24,
                fontFamily="Arial",
                fontWeight="normal",
                align="left",
                lineHeight=1.2,
                fill="#687184",
            ),
            layer(
                "point-2-rule",
                "LINE",
                x=1015,
                y=910,
                width=480,
                height=0,
                zIndex=2,
                points=[0, 0, 480, 0],
                stroke="#e1e3df",
                strokeWidth=2,
            ),
            layer(
                "number-3",
                "TEXT",
                x=900,
                y=975,
                width=90,
                height=80,
                zIndex=2,
                text="03",
                fontSize=62,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1,
                fill="#c6a174",
            ),
            layer(
                "point-3-title",
                "TEXT",
                x=1015,
                y=985,
                width=480,
                height=55,
                zIndex=2,
                text="{{selling_point_3}}",
                fontSize=38,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1.2,
                fill="#202a3f",
            ),
            layer(
                "point-3-description",
                "TEXT",
                x=1015,
                y=1060,
                width=480,
                height=45,
                zIndex=2,
                text="{{sku.selling_point_description_3}}",
                fontSize=24,
                fontFamily="Arial",
                fontWeight="normal",
                align="left",
                lineHeight=1.2,
                fill="#687184",
            ),
        ),
    },
    {
        "id": "20000000-0000-4000-8000-000000000004",
        "name": "产品参数展示",
        "code": "PARAMETER_01",
        "template_type": TemplateType.PARAMETER,
        "status": TemplateStatus.ACTIVE,
        "canvas_width": 1600,
        "canvas_height": 1600,
        "background": {"color": "#f3f5f3"},
        "schema_json": document(
            layer(
                "panel",
                "SHAPE",
                x=70,
                y=110,
                width=520,
                height=1380,
                zIndex=0,
                fill="#ffffff",
                stroke="#dce1dc",
                strokeWidth=2,
                cornerRadius=24,
            ),
            layer(
                "product",
                "IMAGE",
                x=610,
                y=180,
                width=930,
                height=1240,
                zIndex=1,
                assetSource="{{asset.cutout}}",
                fit="contain",
            ),
            layer(
                "heading",
                "TEXT",
                x=125,
                y=205,
                width=410,
                height=60,
                zIndex=2,
                text="PRODUCT PARAMETERS",
                fontSize=27,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1.2,
                fill="#a26332",
            ),
            layer(
                "name",
                "TEXT",
                x=125,
                y=295,
                width=410,
                height=145,
                zIndex=2,
                text="{{product.name}}",
                fontSize=44,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1.12,
                fill="#182238",
            ),
            layer(
                "header-rule",
                "LINE",
                x=125,
                y=485,
                width=410,
                height=0,
                zIndex=2,
                points=[0, 0, 410, 0],
                stroke="#dce1dc",
                strokeWidth=2,
            ),
            layer(
                "material-label",
                "TEXT",
                x=125,
                y=560,
                width=410,
                height=35,
                zIndex=2,
                text="MATERIAL",
                fontSize=21,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1.2,
                fill="#7a8492",
            ),
            layer(
                "material",
                "TEXT",
                x=125,
                y=610,
                width=410,
                height=55,
                zIndex=2,
                text="{{product.material}}",
                fontSize=34,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1.2,
                fill="#273247",
            ),
            layer(
                "row-1-rule",
                "LINE",
                x=125,
                y=710,
                width=410,
                height=0,
                zIndex=2,
                points=[0, 0, 410, 0],
                stroke="#e5e8e4",
                strokeWidth=2,
            ),
            layer(
                "color-label",
                "TEXT",
                x=125,
                y=775,
                width=175,
                height=35,
                zIndex=2,
                text="COLOR",
                fontSize=21,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1.2,
                fill="#7a8492",
            ),
            layer(
                "color",
                "TEXT",
                x=125,
                y=825,
                width=175,
                height=55,
                zIndex=2,
                text="{{product.color}}",
                fontSize=36,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1.2,
                fill="#273247",
            ),
            layer(
                "size-label",
                "TEXT",
                x=335,
                y=775,
                width=200,
                height=35,
                zIndex=2,
                text="SIZE",
                fontSize=21,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1.2,
                fill="#7a8492",
            ),
            layer(
                "size",
                "TEXT",
                x=335,
                y=827,
                width=200,
                height=80,
                zIndex=2,
                text="{{product.length}} ×\n{{product.width}}",
                fontSize=30,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1.15,
                fill="#273247",
            ),
            layer(
                "row-2-rule",
                "LINE",
                x=125,
                y=940,
                width=410,
                height=0,
                zIndex=2,
                points=[0, 0, 410, 0],
                stroke="#e5e8e4",
                strokeWidth=2,
            ),
            layer(
                "sku-label",
                "TEXT",
                x=125,
                y=1005,
                width=410,
                height=35,
                zIndex=2,
                text="SKU",
                fontSize=21,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1.2,
                fill="#7a8492",
            ),
            layer(
                "sku",
                "TEXT",
                x=125,
                y=1055,
                width=410,
                height=90,
                zIndex=2,
                text="{{sku.code}}",
                fontSize=30,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1.15,
                fill="#273247",
            ),
        ),
    },
    {
        "id": "20000000-0000-4000-8000-000000000005",
        "name": "商品与包装展示",
        "code": "PACKAGE_01",
        "template_type": TemplateType.PACKAGE,
        "status": TemplateStatus.ACTIVE,
        "canvas_width": 1600,
        "canvas_height": 1600,
        "background": {"color": "#ffffff"},
        "schema_json": document(
            layer(
                "package",
                "IMAGE",
                x=90,
                y=220,
                width=760,
                height=1100,
                zIndex=1,
                assetSource="{{asset.package}}",
                fit="contain",
            ),
            layer(
                "product",
                "IMAGE",
                x=760,
                y=280,
                width=750,
                height=1000,
                zIndex=2,
                assetSource="{{asset.cutout}}",
                fit="contain",
            ),
            layer(
                "caption",
                "TEXT",
                x=200,
                y=1360,
                width=1200,
                height=100,
                zIndex=3,
                text="Product and package shown exactly as supplied",
                fontSize=30,
                fontFamily="Arial",
                fontWeight="normal",
                align="center",
                lineHeight=1.2,
                fill="#647086",
            ),
        ),
    },
    {
        "id": "20000000-0000-4000-8000-000000000006",
        "name": "细节特写",
        "code": "DETAIL_CLOSEUP_01",
        "template_type": TemplateType.DETAIL,
        "status": TemplateStatus.ACTIVE,
        "canvas_width": 1600,
        "canvas_height": 1600,
        "background": {"color": "#ffffff"},
        "schema_json": document(
            layer(
                "closeup",
                "IMAGE",
                x=100,
                y=100,
                width=1400,
                height=1160,
                zIndex=1,
                assetSource="{{asset.closeup}}",
                fit="cover",
                cornerRadius=24,
            ),
            layer(
                "rule",
                "LINE",
                x=100,
                y=1330,
                width=180,
                height=0,
                zIndex=2,
                points=[0, 0, 180, 0],
                stroke="#ff6433",
                strokeWidth=8,
            ),
            layer(
                "title",
                "TEXT",
                x=320,
                y=1290,
                width=1050,
                height=120,
                zIndex=3,
                text="{{selling_point_1}}",
                fontSize=48,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1.2,
                fill="#172033",
            ),
        ),
    },
)
