from typing import Any

from app.templates.models import TemplateStatus, TemplateType


def layer(layer_id: str, layer_type: str, **values: Any) -> dict[str, Any]:
    return {
        "id": layer_id,
        "type": layer_type,
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0,
        "rotation": 0,
        "opacity": 1,
        "visible": True,
        "locked": False,
        "zIndex": 0,
        **values,
    }


def document(*layers: dict[str, Any]) -> dict[str, Any]:
    return {"schemaVersion": "1.0", "layers": list(layers), "metadata": {"demo": True}}


DEMO_TEMPLATES: tuple[dict[str, Any], ...] = (
    {
        "id": "20000000-0000-4000-8000-000000000001",
        "name": "白底主图",
        "code": "MAIN_WHITE_01",
        "template_type": TemplateType.MAIN,
        "status": TemplateStatus.ACTIVE,
        "canvas_width": 1600,
        "canvas_height": 1600,
        "background": {"color": "#ffffff"},
        "schema_json": document(
            layer(
                "product",
                "IMAGE",
                x=160,
                y=120,
                width=1280,
                height=1280,
                zIndex=1,
                assetSource="{{asset.cutout}}",
                fit="contain",
            )
        ),
    },
    {
        "id": "20000000-0000-4000-8000-000000000002",
        "name": "基础长宽尺寸图",
        "code": "DIMENSION_BASIC_01",
        "template_type": TemplateType.DIMENSION,
        "status": TemplateStatus.ACTIVE,
        "canvas_width": 1600,
        "canvas_height": 1600,
        "background": {"color": "#f7f8fa"},
        "schema_json": document(
            layer(
                "product",
                "IMAGE",
                x=350,
                y=230,
                width=900,
                height=900,
                zIndex=1,
                assetSource="{{asset.cutout}}",
                fit="contain",
            ),
            layer(
                "width-line",
                "LINE",
                x=350,
                y=1210,
                width=900,
                height=30,
                zIndex=2,
                points=[0, 0, 900, 0],
                stroke="#172033",
                strokeWidth=3,
                arrowStart=True,
                arrowEnd=True,
            ),
            layer(
                "width-text",
                "TEXT",
                x=500,
                y=1260,
                width=600,
                height=80,
                zIndex=3,
                text="{{product.width}}",
                fontSize=48,
                fontFamily="Arial",
                fontWeight="bold",
                align="center",
                lineHeight=1.2,
                fill="#172033",
            ),
            layer(
                "height-line",
                "LINE",
                x=260,
                y=300,
                width=30,
                height=760,
                zIndex=2,
                points=[0, 0, 0, 760],
                stroke="#172033",
                strokeWidth=3,
                arrowStart=True,
                arrowEnd=True,
            ),
            layer(
                "height-text",
                "TEXT",
                x=30,
                y=650,
                width=190,
                height=80,
                zIndex=3,
                text="{{product.height}}",
                fontSize=42,
                fontFamily="Arial",
                fontWeight="bold",
                align="right",
                lineHeight=1.2,
                fill="#172033",
            ),
        ),
    },
    {
        "id": "20000000-0000-4000-8000-000000000003",
        "name": "三个核心卖点",
        "code": "SELLING_POINT_01",
        "template_type": TemplateType.SELLING_POINT,
        "status": TemplateStatus.ACTIVE,
        "canvas_width": 1600,
        "canvas_height": 1600,
        "background": {"color": "#ffffff"},
        "schema_json": document(
            layer(
                "product",
                "IMAGE",
                x=100,
                y=260,
                width=780,
                height=1040,
                zIndex=1,
                assetSource="{{asset.cutout}}",
                fit="contain",
            ),
            layer(
                "title",
                "TEXT",
                x=920,
                y=260,
                width=560,
                height=160,
                zIndex=2,
                text="{{product.name}}",
                fontSize=58,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1.15,
                fill="#172033",
            ),
            layer(
                "point-1",
                "TEXT",
                x=940,
                y=580,
                width=500,
                height=110,
                zIndex=2,
                text="01  {{selling_point_1}}",
                fontSize=38,
                fontFamily="Arial",
                fontWeight="semibold",
                align="left",
                lineHeight=1.2,
                fill="#263149",
            ),
            layer(
                "point-2",
                "TEXT",
                x=940,
                y=760,
                width=500,
                height=110,
                zIndex=2,
                text="02  {{selling_point_2}}",
                fontSize=38,
                fontFamily="Arial",
                fontWeight="semibold",
                align="left",
                lineHeight=1.2,
                fill="#263149",
            ),
            layer(
                "point-3",
                "TEXT",
                x=940,
                y=940,
                width=500,
                height=110,
                zIndex=2,
                text="03  {{selling_point_3}}",
                fontSize=38,
                fontFamily="Arial",
                fontWeight="semibold",
                align="left",
                lineHeight=1.2,
                fill="#263149",
            ),
        ),
    },
    {
        "id": "20000000-0000-4000-8000-000000000004",
        "name": "产品参数展示",
        "code": "PARAMETER_01",
        "template_type": TemplateType.PARAMETER,
        "status": TemplateStatus.ACTIVE,
        "canvas_width": 1600,
        "canvas_height": 1600,
        "background": {"color": "#f5f7fa"},
        "schema_json": document(
            layer(
                "panel",
                "SHAPE",
                x=100,
                y=140,
                width=650,
                height=1320,
                zIndex=0,
                fill="#ffffff",
                stroke="#e1e6ed",
                strokeWidth=2,
                cornerRadius=28,
            ),
            layer(
                "product",
                "IMAGE",
                x=800,
                y=220,
                width=700,
                height=1120,
                zIndex=1,
                assetSource="{{asset.cutout}}",
                fit="contain",
            ),
            layer(
                "heading",
                "TEXT",
                x=170,
                y=240,
                width=500,
                height=100,
                zIndex=2,
                text="PRODUCT PARAMETERS",
                fontSize=34,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1.2,
                fill="#ff6433",
            ),
            layer(
                "name",
                "TEXT",
                x=170,
                y=360,
                width=500,
                height=160,
                zIndex=2,
                text="{{product.name}}",
                fontSize=54,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1.15,
                fill="#172033",
            ),
            layer(
                "material",
                "TEXT",
                x=170,
                y=650,
                width=500,
                height=80,
                zIndex=2,
                text="Material  {{product.material}}",
                fontSize=30,
                fontFamily="Arial",
                fontWeight="normal",
                align="left",
                lineHeight=1.2,
                fill="#526078",
            ),
            layer(
                "color",
                "TEXT",
                x=170,
                y=780,
                width=500,
                height=80,
                zIndex=2,
                text="Color  {{product.color}}",
                fontSize=30,
                fontFamily="Arial",
                fontWeight="normal",
                align="left",
                lineHeight=1.2,
                fill="#526078",
            ),
            layer(
                "size",
                "TEXT",
                x=170,
                y=910,
                width=500,
                height=140,
                zIndex=2,
                text="Size  {{product.length}} × {{product.width}} × {{product.height}}",
                fontSize=30,
                fontFamily="Arial",
                fontWeight="normal",
                align="left",
                lineHeight=1.3,
                fill="#526078",
            ),
            layer(
                "weight",
                "TEXT",
                x=170,
                y=1090,
                width=500,
                height=80,
                zIndex=2,
                text="Weight  {{product.weight}}",
                fontSize=30,
                fontFamily="Arial",
                fontWeight="normal",
                align="left",
                lineHeight=1.2,
                fill="#526078",
            ),
            layer(
                "sku",
                "TEXT",
                x=170,
                y=1220,
                width=500,
                height=80,
                zIndex=2,
                text="SKU  {{sku.code}}",
                fontSize=26,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1.2,
                fill="#172033",
            ),
        ),
    },
    {
        "id": "20000000-0000-4000-8000-000000000005",
        "name": "商品与包装展示",
        "code": "PACKAGE_01",
        "template_type": TemplateType.PACKAGE,
        "status": TemplateStatus.ACTIVE,
        "canvas_width": 1600,
        "canvas_height": 1600,
        "background": {"color": "#ffffff"},
        "schema_json": document(
            layer(
                "package",
                "IMAGE",
                x=90,
                y=220,
                width=760,
                height=1100,
                zIndex=1,
                assetSource="{{asset.package}}",
                fit="contain",
            ),
            layer(
                "product",
                "IMAGE",
                x=760,
                y=280,
                width=750,
                height=1000,
                zIndex=2,
                assetSource="{{asset.cutout}}",
                fit="contain",
            ),
            layer(
                "caption",
                "TEXT",
                x=200,
                y=1360,
                width=1200,
                height=100,
                zIndex=3,
                text="Product and package shown exactly as supplied",
                fontSize=30,
                fontFamily="Arial",
                fontWeight="normal",
                align="center",
                lineHeight=1.2,
                fill="#647086",
            ),
        ),
    },
    {
        "id": "20000000-0000-4000-8000-000000000006",
        "name": "细节特写",
        "code": "DETAIL_CLOSEUP_01",
        "template_type": TemplateType.DETAIL,
        "status": TemplateStatus.ACTIVE,
        "canvas_width": 1600,
        "canvas_height": 1600,
        "background": {"color": "#ffffff"},
        "schema_json": document(
            layer(
                "closeup",
                "IMAGE",
                x=100,
                y=100,
                width=1400,
                height=1160,
                zIndex=1,
                assetSource="{{asset.closeup}}",
                fit="cover",
                cornerRadius=24,
            ),
            layer(
                "rule",
                "LINE",
                x=100,
                y=1330,
                width=180,
                height=0,
                zIndex=2,
                points=[0, 0, 180, 0],
                stroke="#ff6433",
                strokeWidth=8,
            ),
            layer(
                "title",
                "TEXT",
                x=320,
                y=1290,
                width=1050,
                height=120,
                zIndex=3,
                text="{{selling_point_1}}",
                fontSize=48,
                fontFamily="Arial",
                fontWeight="bold",
                align="left",
                lineHeight=1.2,
                fill="#172033",
            ),
        ),
    },
)
